---
version: 1
disable_existing_loggers: False
formatters:
  default:
    (): 'uvicorn.logging.DefaultFormatter'
    fmt: '%(asctime)s %(levelprefix)-9s %(name)s - %(message)s'
    use_colors: True

  access:
    (): 'uvicorn.logging.AccessFormatter'
    fmt: '%(asctime)s %(levelprefix)-9s %(name)s -: %(client_addr)s - "%(request_line)s" %(status_code)s'
    use_colors: True

  simple:
    fmt: 'coool %(levelprefix)-9s %(name)s -: %(message)s'

handlers:
  console:
    class: logging.StreamHandler
    formatter: default
    stream: ext://sys.stderr

  access:
    class: logging.StreamHandler
    formatter: access
    stream: ext://sys.stdout

  custom:
    class: app.logging.QLogHandler
    formatter: simple


loggers:
  "":
    level: DEBUG
    handlers:
      - console
    propagate: False
  hello:
    level: DEBUG
    handlers:
      - custom
    propagate: False
  fastapi:
    level: DEBUG
    handlers:
      - console
    propagate: False
  uvicorn:
    level: INFO
    handlers:
      - console
    propagate: False
  uvicorn.error:
    level: INFO
    handlers:
      - console
    propagate: False
  uvicorn.access:
    level: INFO
    propagate: False
    handlers:
      - console
